version: '3.8'
services:
  tpot:
    image: dtagdevsec/tpotce:24.04.1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "1-65535:1-65535/tcp"
      - "1-65535:1-65535/udp"
    volumes:
      - tpot-data:/data
    environment:
      - TZ=Europe/Berlin
volumes:
  tpot-data:
