version: '3.8'
services:
  cowrie:
    image: cowrie/cowrie:latest
    restart: unless-stopped
    ports:
      - "2222:2222/tcp"
    volumes:
      - cowrie-data:/cowrie/var/lib/cowrie/tty/
volumes:
  cowrie-data:
