version: '3.8'
services:
  dionaea:
    image: dinotools/dionaea:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - dionaea-data:/opt/dionaea/var/lib/dionaea
volumes:
  dionaea-data:
