version: '3.8'
services:
  cowrie-ml:
    build: .
    restart: unless-stopped
    ports:
      - "2222:2222/tcp"  # Puerto SSH expuesto
    volumes:
      - cowrie-ml-data:/cowrie/var/lib/cowrie/
      - cowrie-ml-logs:/cowrie/var/log/cowrie/
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Berlin
volumes:
  cowrie-ml-data:
  cowrie-ml-logs:
